= Employee Rostering Optimization as a Service

An end-to-end https://www.optaplanner.org/[OptaPlanner] web application ready to deploy on https://www.openshift.com/[OpenShift 3].

See https://www.youtube.com/watch?v=sOWC4qrXxFk[the video demo].

== Running on OpenShift Dedicated (paid edition)

=== Prerequisites

. Install https://www.openshift.org/download.html[the oc client tools]

To copy-paste your command, go to https://manage.openshift.com/[the OpenShift Online web console] and look for _Help_ > _Command line tools_.

=== Setup

. Login to OpenShift Dedicated from command line:
+
----
oc login https://api.YOUR_SERVER.openshift.com --token=<tokenId>
----
+
If you don't know your `<tokenId>`, log in at https://manage.openshift.com/[the OpenShift web console]
and look for _Help_ > _Command Line Tools_.

. Create, build and deploy the project.
+
----
./provision.sh setup --project-suffix myDemo
----
+
The `--project-suffix` is optional.

. It should now be building the pod and running it on OpenShift.
Go to https://manage.openshift.com/[the OpenShift Online web console]
to get the `*.openshiftapps.com` URL to visit.

=== Updates

To build and deploy new changes, use:
----
./provision.sh deploy
----

=== Deletion

To delete the OpenShift application and project, run:
----
./provision.sh delete
----

== Running on OpenShift Online (free edition)

This is not possible to due to resource limitations.

== Running on a local OpenShift Origin

. If you just installed oc client tools, follow the https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md[OpenShift Local Cluster Management] docs to get `oc cluster (up|down)` working.
. `oc cluster up`
. `oc login`, enter `developer` for both username and password when prompted
. `oc new-project optashift-employee-rostering`
// TODO Change to wildfly:11.0 once it is available
. `oc new-app --image-stream="openshift/wildfly:10.1" https://github.com/kiegroup/optashift-employee-rostering.git#master`

To trigger a new build with the latest updates from the master branch, run

----
oc start-build optashift-employee-rostering
----

To delete the OpenShift application and project, run

----
oc delete project optashift-employee-rostering
----

== Development

=== Code formatter

Both IntelliJ and Eclipse formatters are available here: https://github.com/kiegroup/droolsjbpm-build-bootstrap/tree/master/ide-configuration

=== Building from source

```
mvn clean install
```

Under the covers, OpenShift builds activate the `openshift` profile.
To reproduce locally, add it explicitly (the `provision.sh` script already does this):

```
mvn clean package -P openshift
```

=== IntelliJ IDEA 2017.3 (and above)

. https://youtrack.jetbrains.com/issue/IDEA-171158[IntelliJ 2017.3 now supports the new GWT plugin]
. `TODO: Test and document`


=== IntelliJ IDEA 2017.2 (and below) + CLI

The steps below make sure that the GWT Codeserver will recompile the application after files under `src/main/resources` are saved.

. Import the maven project by choosing the root `pom.xml` file and selecting `Open as project`
. Install the `Save Actions` plugin
. Restart IntelliJ (required after installing the plugin)
. Under `Other settings`, go to the `Save Actions` submenu and check either the first or the second options in the `General` section
. Check the `Compile file` option in the `Build actions` section

After configuring the `Save Actions` plugin, you should be able to start Wildfly and deploy the application from the CLI. Note that if you need to restart the GWT Code Server, it's not mandatory to restart Wildfly.

```
mvn -N wildfly:start wildfly:deploy
mvn gwt:codeserver
```

To stop the Wildfly server, use `mvn -N wildfly:shutdown`.

=== Eclipse
. `TODO: Document`

