= Employee Rostering Optimization as a Service

An example https://www.optaplanner.org/[OptaPlanner] webapp ready to deploy on https://www.openshift.com/[OpenShift 3].


== Running on OpenShift

=== Prerequisites

. Install https://www.openshift.org/download.html[the oc client tools] and log in.

. Login with `oc login <url> <token>` from the command line.
+
To copy-paste your command, go to https://manage.openshift.com/[the OpenShift Online web console] and look for _Help_ > _Command line tools_.

=== Binary S2I: build locally and deploy to OpenShift Online

Create the project, build the `war` file locally and provision it on OpenShift:

```
./provision.sh setup employee-rostering --binary
```

That's it, it should now be running on the web.
Go to https://manage.openshift.com/[the OpenShift Online web console]
to get the `*.openshiftapps.com` URL.

Later, you can just run this command to deploy new code changes:

```
./provision.sh deploy employee-rostering --binary
```


=== Normal S2I: build from source on OpenShift Dedicated

WARNING: This does not work on OpenShift Online due to resource limits.

Build it entirely from source on OpenShift and provision it there:

```
./provision.sh deploy employee-rostering
```


=== Delete the OpenShift application and project

```
./provision.sh delete employee-rostering
```


== Development

=== Building from source

```
mvn clean install
```

Under the covers, OpenShift builds activate the `openshift` profile.
To reproduce locally, add it explicitly (the `provision.sh` script already does this):

```
mvn clean package -P openshift
```

=== IntelliJ IDEA run configurations

. https://youtrack.jetbrains.com/issue/IDEA-171158[IntelliJ does not support the new GWT plugin yet]
. Create a new JBoss run configuration to a local WildFly instance:
.. In the _Before launch_ list, remove `Make project`
.. In the _Before launch_ list, add `Run Maven goal` on the root pom with arguments `clean install -Dgwt.draftCompile`
.. In the _Deployment_ tab, in _Deploy at startup_, add `optashift-employee-rostering-webapp:war exploded`.


=== GWT Super Dev Mode from the command line

. Download http://wildfly.org/downloads/[WildFly]
.. Unzip it into `local/appserver/` in the project root.
The `local` directory is ignored by Git.
.. Create a symlink:
+
```
cd local/appserver/
ln -s wildfly-10.1.0.Final/ wildfly
```
. Run super dev mode in the root project:
+
```
mvn gwt:devmode
```
+
If you unzipped WildFly to a different directory, use:
+
```
mvn gwt:devmode -Dwildfly.home=/.../wildfly
```
