= Employee Rostering Optimization as a Service

An example https://www.optaplanner.org/[OptaPlanner] webapp ready to deploy on https://www.openshift.com/[OpenShift 3].

See https://www.youtube.com/watch?v=sOWC4qrXxFk[the video demo].

== Running on OpenShift

=== Prerequisites

. Install https://www.openshift.org/download.html[the oc client tools]

To copy-paste your command, go to https://manage.openshift.com/[the OpenShift Online web console] and look for _Help_ > _Command line tools_.

=== Locally with OpenShift Origin

. If you just installed oc client tools, follow the https://github.com/openshift/origin/blob/master/docs/cluster_up_down.md[OpenShift Local Cluster Management] docs to get `oc cluster (up|down)` working.
. `oc cluster up`
. `oc login`, enter "developer" for both username and password when prompted
. `oc new-project <your-project-name>` (ex: "openshift", must consist of only lowercase letters, numbers and hypens)
. `oc new-app --image-stream="openshift/wildfly:10.1" https://github.com/kiegroup/optashift-employee-rostering.git#master`

To trigger a new build with the latest updates from the master branch, run

`oc start-build optashift-employee-rostering`

To delete the OpenShift application and project, run

`oc delete project <your-project-name>`

=== OpenShift Dedicated

. Login to OpenShift Dedicated from command line
+
(With username and password)
+
`oc login -u=<username> -p=<password> --server=<your-openshift-server> --insecure-skip-tls-verify`
+
(With OAuth token)
+
`oc login <https://api.your-openshift-server.com> --token=<tokenID>`

. `oc new-project <your-project-name>` (ex: "openshift", must consist of only lowercase letters, numbers and hypens)
. `oc new-app --image-stream="openshift/wildfly:10.1" https://github.com/kiegroup/optashift-employee-rostering.git#master`

To trigger a new build with the latest updates from the master branch, run

`oc start-build optashift-employee-rostering`

To delete the OpenShift application and project, run

`oc delete project <your-project-name>`

=== OpenShift Online

Login to OpenShift Online from command line

(With username and password)

`oc login -u=<username> -p=<password> --server=<your-openshift-server> --insecure-skip-tls-verify`

(With OAuth token)

`oc login <https://api.your-openshift-server.com> --token=<tokenID>`

Create the project, build the `war` file locally and provision it on OpenShift:

`./provision.sh setup employee-rostering --binary`

That's it, it should now be running on the web.
Go to https://manage.openshift.com/[the OpenShift Online web console]
to get the `*.openshiftapps.com` URL.

Later, you can just run this command to deploy new code changes:

`./provision.sh deploy employee-rostering --binary`

Or this command to delete the OpenShift Online application and project:

`./provision.sh delete employee-rostering`

== Development

=== Building from source

```
mvn clean install
```

Under the covers, OpenShift builds activate the `openshift` profile.
To reproduce locally, add it explicitly (the `provision.sh` script already does this):

```
mvn clean package -P openshift
```

=== IntelliJ IDEA run configurations

. https://youtrack.jetbrains.com/issue/IDEA-171158[IntelliJ does not support the new GWT plugin yet]
. Create a new JBoss run configuration to a local WildFly instance:
.. In the _Before launch_ list, remove `Make project`
.. In the _Before launch_ list, add `Run Maven goal` on the root pom with arguments `clean install -Dgwt.draftCompile`
.. In the _Deployment_ tab, in _Deploy at startup_, add `optashift-employee-rostering-webapp:war exploded`.


=== GWT Super Dev Mode from the command line

```
mvn -N wildfly:start wildfly:deploy
mvn gwt:codeserver
```

To stop the wildfly server, use `mvn -N wildfly:shutdown`.

. Download http://wildfly.org/downloads/[WildFly]
.. Unzip it into `local/appserver/` in the project root.
The `local` directory is ignored by Git.
.. Create a symlink:
+
```
cd local/appserver/
ln -s wildfly-10.1.0.Final/ wildfly
```
. Run super dev mode in the root project:
+
```
mvn gwt:devmode
```
+
If you unzipped WildFly to a different directory, use:
+
```
mvn gwt:devmode -Dwildfly.home=/.../wildfly
```
