= Employee Rostering Optimization as a Service

image:https://sonarcloud.io/api/project_badges/measure?project=optaweb-employee-rostering&metric=alert_status[
"Quality Gate Status", link="https://sonarcloud.io/dashboard?id=optaweb-employee-rostering"]
image:https://sonarcloud.io/api/project_badges/measure?project=optaweb-employee-rostering&metric=reliability_rating[
"Reliability Rating", link="https://sonarcloud.io/dashboard?id=optaweb-employee-rostering"]
image:https://sonarcloud.io/api/project_badges/measure?project=optaweb-employee-rostering&metric=security_rating[
"Security Rating", link="https://sonarcloud.io/dashboard?id=optaweb-employee-rostering"]
image:https://sonarcloud.io/api/project_badges/measure?project=optaweb-employee-rostering&metric=sqale_rating[
"Maintainability Rating", link="https://sonarcloud.io/dashboard?id=optaweb-employee-rostering"]
image:https://sonarcloud.io/api/project_badges/measure?project=optaweb-employee-rostering&metric=ncloc[
"Lines of Code", link="https://sonarcloud.io/dashboard?id=optaweb-employee-rostering"]
image:https://sonarcloud.io/api/project_badges/measure?project=optaweb-employee-rostering&metric=coverage[
"Coverage", link="https://sonarcloud.io/dashboard?id=optaweb-employee-rostering"]

An end-to-end https://www.optaplanner.org/[OptaPlanner] web application ready to deploy on https://www.openshift.com/[OpenShift 4].

See https://www.youtube.com/watch?v=sOWC4qrXxFk[the video demo].

== Building

Build the project with maven in the project's root directory:

[source,shell]
----
mvn clean install -DskipTests -DskipITs
----

== Running

After building the project, run the application with:

[source,shell]
----
java -jar employee-rostering-standalone/target/employee-rostering-standalone-*-exec.jar --spring.profiles.active=dev
----

Then open http://localhost:8080/ to see the web application.

Alternatively, run `npm start` in `employee-rostering-frontend` to start the frontend in one terminal,
and run `mvn spring-boot:run` in `employee-rostering-backend` to start the backend in another terminal.

=== Use a different port

To run on an another port use `--server.port=...`:

[source,shell]
----
java -jar employee-rostering-standalone/target/employee-rostering-standalone-*-exec.jar --spring.profiles.active=dev --server.port=18080
----

== Benchmark Application

After building the project above, run the benchmark application with:

[source,shell]
----
java -jar employee-rostering-benchmark/target/employee-rostering-benchmark-*.jar
----

Note: make sure to run the project application and benchmark application on different ports if they are run
simultaneously.

After benchmarking is complete, a benchmark report will be generated in the `local/benchmarkReport` directory.
Open the `index.html` file in your browser to view the benchmark results.

=== Configure the benchmarker

To configure the benchmarker, modify the `employeeRosteringBenchmarkConfig.xml` file found in the
`employee-rostering-benchmark/src/main/resources` directory. Make sure to rebuild the project after modifying the
config file for the benchmarker changes to be applied.

Refer to the https://docs.optaplanner.org/latestFinal/optaplanner-docs/html_single/index.html#benchmarker[OptaPlanner
 Docs] for more information on benchmark tweaking.

== Running on a local OpenShift cluster

Use https://developers.redhat.com/products/codeready-containers[Red Hat CodeReady Containers]
to easily set up a single-node OpenShift 4 cluster on your local computer.

.Prerequisites
You have successfully built the project with Maven.

.Procedure
1. To install CRC, follow the https://code-ready.github.io/crc/[Getting Started Guide].

2. When the cluster has started,

a. add oc command-line interface to your `$PATH`:
+
[source,shell]
----
eval $(crc oc-env)
----

b. log in as "developer".

3. Create a new project
+
[source,subs="quotes"]
----
oc new-project _project_name_
----

4. Run the script:
+
[source,shell]
----
./provision.sh
----

=== Updating the deployed application with local changes

==== Backend

Change the source code and build the backend module with Maven.
Then start OpenShift build:

[source,shell]
----
cd employee-rostering-backend
oc start-build backend --from-dir=. --follow
----

==== Frontend

Change the source code and build the frontend module with npm.
Then start OpenShift build:

[source,shell]
----
cd employee-rostering-frontend
oc start-build frontend --from-dir=docker --follow
----

== Development

=== Code formatter

Both IntelliJ and Eclipse formatters are available here: https://github.com/kiegroup/droolsjbpm-build-bootstrap/tree/master/ide-configuration
