= Employee Rostering Optimization as a Service

image:https://sonarcloud.io/api/project_badges/measure?project=optaweb-employee-rostering&metric=alert_status[
"Quality Gate Status", link="https://sonarcloud.io/dashboard?id=optaweb-employee-rostering"]
image:https://sonarcloud.io/api/project_badges/measure?project=optaweb-employee-rostering&metric=reliability_rating[
"Reliability Rating", link="https://sonarcloud.io/dashboard?id=optaweb-employee-rostering"]
image:https://sonarcloud.io/api/project_badges/measure?project=optaweb-employee-rostering&metric=security_rating[
"Security Rating", link="https://sonarcloud.io/dashboard?id=optaweb-employee-rostering"]
image:https://sonarcloud.io/api/project_badges/measure?project=optaweb-employee-rostering&metric=sqale_rating[
"Maintainability Rating", link="https://sonarcloud.io/dashboard?id=optaweb-employee-rostering"]
image:https://sonarcloud.io/api/project_badges/measure?project=optaweb-employee-rostering&metric=ncloc[
"Lines of Code", link="https://sonarcloud.io/dashboard?id=optaweb-employee-rostering"]
image:https://sonarcloud.io/api/project_badges/measure?project=optaweb-employee-rostering&metric=coverage[
"Coverage", link="https://sonarcloud.io/dashboard?id=optaweb-employee-rostering"]

An end-to-end https://www.optaplanner.org/[OptaPlanner] web application ready to deploy on https://www.openshift.com/[OpenShift 3].

See https://www.youtube.com/watch?v=sOWC4qrXxFk[the video demo].

== Building

Build the project with maven in the project's root directory:

[source,shell]
----
mvn clean install -DskipTests
----

== Running

After building the project, run the application with:

[source,shell]
----
java -jar employee-rostering-distribution/target/employee-rostering-distribution-*.jar
----

Then open http://localhost:8080/ to see the web application.

Alternatively, run `npm start` in `employee-rostering-frontend` to start the frontend in one terminal,
and run `mvn spring-boot:run` in `employee-rostering-backend` to start the backend in another terminal.

=== Use a different port

To run on an another port use `--server.port=...`:

[source,shell]
----
java -jar employee-rostering-distribution/target/employee-rostering-distribution-*.jar --server.port=18080
----

== Development

=== Code formatter

Both IntelliJ and Eclipse formatters are available here: https://github.com/kiegroup/droolsjbpm-build-bootstrap/tree/master/ide-configuration
