[id='er-individualroster-proc']
= Viewing employee shifts

You can view the assigned shifts for particular employees in an employee-centric table. The information is the same as the Shift Roster, but the viewing format might be more convenient for informing employees about their assigned shifts.

.Procedure
. To view a table of employees and shifts, click the *Availability Roster* tab.
+
In the top left part of the window, you can see the dates for which the roster is displayed. To view other weeks, you can use the *<* and *>* buttons next to the *Week of* field. Alternatively, you can click the date field and change the date to view the week that includes this date.
+
You can see the numbers of currently visible employees in the top right part of the browser window, for example, `1-10 of 34`. You can use the *<* and *>* buttons next to the numbers to display other employees in the list. 

In the draft period, the borders of boxes representing shifts are dotted lines. In the published periods, the borders are unbroken lines.
